### ISSUE TITLE
feature: noop if no supported options found.

### ISSUE THREAD

**Issue by BerkeleyTrue** [marcuswestin/store.js#129]
Tried to use this package in a universal(read: isomorphic) app. It threw `cannot read property 'documentElement' of undefined`.

What I was hoping that this package would just noop in the server and work as expected in the browser. I would be down to form a PR for this. It just involves checking for property existence.

**Comment by marcuswestin** [comment]
Hi Berkeley,

Is `store.disabled` true?

On Tue, Jul 14, 2015 at 7:11 PM, Berkeley Martinez <notifications@github.com

**Comment by BerkeleyTrue** [comment]
Its the default false as it throws at https://github.com/marcuswestin/store.js/blob/master/store.js#L92 before it gets a chance to check if it is enabled or not.

**Comment by Marsup** [comment]
Did you find a solution to that ? Also trying to make it work in a webpack build.

**Comment by BerkeleyTrue** [comment]
Nope. Ended up abandoning using localStorage all together. Ill need to find a solution in the future but I think I will create a library for my specific use case.

**Comment by BerkeleyTrue** [comment]
@marcuswestin Is this a feature you would like to support? I have a working version which only requires two lines of code.

**Comment by whitehat101** [comment]
I'm sure someone on the Internet would appreciate your two lines of code, even if it isn't ultimately merged. I'm curious about your use case for loading this in an environment where you expect it not to work, but I expect it simplifies more complicated problems.

As long as there isn't significant code to support such an environment (*two lines hardly sounds significant*), I expect it would be a reasonable candidate for a merge.

Is your server just a regular Node process?

**Comment by BerkeleyTrue** [comment]
It's an isomorphic app, and localStorage is only required on the client so noop's on the server are exactly what I want.

**Comment by marcuswestin** [comment]
See https://github.com/marcuswestin/store.js/blob/master/tests/node-test-runner.js for example usage with a node compatible localstorage module.

**Comment by BerkeleyTrue** [comment]
@marcuswestin Thanks for the release! 

Happy Coding!

**Comment by marcuswestin** [comment]
Store.js v2.0 has been released with pluggable fallback backing storages which ensure that store.js always works in any environment.

If you update to the [latest version](https://github.com/marcuswestin/store.js/blob/master/dist/store.everything.min.js) you will automatically get this functionality plus a bunch more :)

**Comment by BerkeleyTrue** [comment]
@marcuswestin Thanks for the updates. While the feature additions do add a lot of functionality, they double the size of the minimal file. We may just stick to the 1.0 branch. Is there any plan to support that branch (not that we have had any issues) or is the 2.0 branch the only one going to be supported?

**Comment by marcuswestin** [comment]
I think we should figure out how to get the v2 build down in size instead :) I'll create an issue for that!

**Comment by BerkeleyTrue** [comment]
👍

**Comment by marcuswestin** [comment]
@BerkeleyTrue: If you gzip the old store.min.js and the new store.modern.min.js the difference is size is ~1KB. Is that still a no-go for you? Basically you're looking at a ~3kb download with the additional functionalities of v2.0 included.

Either way, we should definitely make a point out of getting the build size down since it does affect the js runtime performance too. I've created an experimental branch that creates a minimal build without plugins, and it's almost at the same size already: https://github.com/marcuswestin/store.js/tree/minimal.

I think there are two additional possible savings that should get it down to parity:
- Allow uglifyjs to mangle property names (store.js v1 did much of this manually by using almost exclusively locally scoped variables instead of objects)
- Create a minimal build which doesn't depend on the browserify require module runtime, but uses minimal file concatenation of store-engine.js and a minimal-build.js.

We may even be able to make it smaller I think!

**Comment by BerkeleyTrue** [comment]
Yeah 1kb is much more manageable.

The minimal one also sounds great. I know we won't be using any of the plugin architecture. I mainly chose this library for SSR and to get a few additional features on top of localStorage.
