### ISSUE TITLE
New release needed please!

### ISSUE THREAD

**Issue by ebergama** [marcuswestin/store.js#139]
Hi! I love your tool and I saw a problem with the 'define' function call for register the module that is solved after the latest release.
Can you make a new release please? :+1:

**Comment by marcuswestin** [comment]
Fixed with v1.3.19 in c6c006eee1811.

I've been gone a long time. Really not appropriate as a maintainer. My bad, sorry for the long wait, thanks for all the patience, and I hope you'll all find good use of upcoming changes! (See https://github.com/marcuswestin/store.js/blob/master/Roadmap.md for details)
