### ISSUE TITLE
storage.load crashes in IE6

### ISSUE THREAD

**Issue by langming701** [marcuswestin/store.js#167]
what 's the method of element.load?

**Comment by marcuswestin** [comment]
Store.js v2 was just released, and it has automated tests for IE6 which do not crash. Please use a build from the new version of store.js (see [dist/](dist/) - I recommend store.v1-backcompat.min.js or store.legacy.min.js for IE6+ support), and then include more info if the bug persists so that I can reproduce it myself.

Thanks!

**Comment by marcuswestin** [comment]
See https://github.com/marcuswestin/store.js/blob/master/README.md for more info
