### ISSUE TITLE
Compression plugin

### ISSUE THREAD

**Issue by marcuswestin** [marcuswestin/store.js#183]
See https://news.ycombinator.com/item?id=13753527

**Comment by marcuswestin** [comment]
See #154

**Comment by w33ble** [comment]
Having just used `lz-string` in a couple projects, and seeing that adding plugins to store.js looks really easy, I thought I might take a stab at creating this plugin. 

Did you intend to add this as a plugin that ships with store.js, in the `plugins` folder? If so, how would you like to handle the `lz-string` dependency? Or were you thinking about doing compression some other way?

**Comment by marcuswestin** [comment]
Haven't thought about it! What do you think is the right answer?

**Comment by w33ble** [comment]
Seems odd to muck up an otherwise dependency-free library with something not everyone needs. Personally, I'd probably create a separate repo, or probably org, and put all the plugins in there. Then plugins and stores can all be their own things, and users can just `npm install` whatever plugins they need. For example, maybe `npm install store store-plugin-defaults store-plugin-compression store-storage-leveldb`. You can still ship a batteries included build somewhere if you want of course, to make downloads and getting started easier. 

I don't know if you want to take things that far though, or if it's worth the maintenance overhead. Maybe a peer dependency is good enough for now? It's your project, you tell me what you want ;)

**Comment by w33ble** [comment]
As far as using lz-string, there's a third, dirtier option too. You could just toss the library in the `lib` folder like you did with json2. When minified, it's pretty small: https://unpkg.com/lz-string@1.4.4/libs/lz-string.min.js

**Comment by marcuswestin** [comment]
I actually don't think that's very dirty at all. Let's do that! And if/when there's a dependency that that's too big and requires an alternative approach we can figure that out then and easily port over current plugin dependencies.

Let's include the unminified version, since the build will minify it for us.
