### ISSUE TITLE
Struggling with basic usage in a HTML page

### ISSUE THREAD

**Issue by mushfek0001** [marcuswestin/store.js#238]
Hi,

I'm trying to use store.js as a simple frontend cache in a HTML using the <script> tag. I've done the following as mentioned in the doc
```
<script src="path/to/my/store.everything.min.js"></script>
<script>
var store = require('store')
store.set('user', { name:'Marcus' })
store.get('user').name == 'Marcus'
</script>
```

But I've got `Uncaught ReferenceError: require is not defined`. Then I've added require.js 2.3.3 using the script tag as well before store.legacy.min.js but now getting this instead
```
Uncaught Error: Module name "store" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded
    at makeError (require-2.3.3.js:168)
    at Object.localRequire [as require] (require-2.3.3.js:1436)
    at requirejs (require-2.3.3.js:1797)
    at home.html:10
```

I am new to JavaScript so can someone please explain what am I doing wrong?

**Comment by marcuswestin** [comment]
Just remove "var store = require('store')" from the example above and it
should work

**Comment by marcuswestin** [comment]
(and remove require.js)

**Comment by mushfek0001** [comment]
Thanks for the fast response. Could you please help me a little more? If I use store by default it uses localStorage but how can I use other plugins? I mean I only want to use memoryStorage. How can I configure storage to do that?

**Comment by marcuswestin** [comment]
Sure :)

If you want to make a custom build you'll need to be using a js
package/module system instead of a script tag. If you're very new to js
development then this may take you a bit of effort to get set up, but it's
the best way to make it happen and you'll definitely want to learn this
sooner or later anyway. I recommend webpack - Google it (or any of its
alternatives) for tutorials.

Once you have that up and running your just follow the instructions here:
https://github.com/marcuswestin/store.js/blob/master/README.md#user-content-make-your-own-build
.

One alternative is to clone this repo and compile your own custom build,
then use that in a script tag. I may add instructions for that later.

Best of luck!

**Comment by alrick** [comment]
Hey there!

Maybe you should update the README accordingly or am I missing something?

**Comment by marcuswestin** [comment]
If you update the readme and create a pull request I'll merge it in :)

**Comment by alrick** [comment]
#246 

Here you go ;)
