### ISSUE TITLE
How to store a file?

### ISSUE THREAD

**Issue by switchy7** [marcuswestin/store.js#296]
Hello, how can i store a JS file and then run it from localstorage with store.js help?

**Comment by switchy7** [comment]
no one can help? please

**Comment by tafengnanhai** [comment]
store js file's  content (string type), and then use eval() function to recover it

**Comment by switchy7** [comment]
can you please write example of the code i am noob

**Comment by tafengnanhai** [comment]
var jsContent = 'alert("test1");alert("test2");'; // jsContent is from the content of your js file. This is just a example. You can get the content through js or copy the content directly
store.set("jsContent", jsContent);
eval(store.get("jsContent")); // eval() function will recover the js file's execution

**Comment by switchy7** [comment]
but when you store to local storage the string and then execute it, can you run some system files?

**Comment by tafengnanhai** [comment]
i can not understand your discription very clearly, mybe cannot. Or others can answer it?

**Comment by switchy7** [comment]
i need to run calculator on windows system that is possible?

**Comment by switchy7** [comment]
calc.exe file

**Comment by tafengnanhai** [comment]
you use store.js in desktop application(.exe) or through webbrowser? if it's webbrowser, i think it cannot work.

**Comment by switchy7** [comment]
from webbrowser why not? that is not possible to store an .exe file? or .js file? and then run it?

**Comment by tafengnanhai** [comment]
webbrowser can not run .exe file directly.

**Comment by switchy7** [comment]
and the *.js file that will run exe?

**Comment by marcuswestin** [comment]
Browsers are built as security sandboxes to prevent webpages from having access to any system files.

You cannot make a webpage execute anything on your machine, so what you want to do is not possible.

(this is by design - if you think about it, it would be a security risk to you if any webpage you visited was able to execute arbitrary programs on your computer. Simply visiting evil-page.com could immediately start executing things on your computer to benefit them or harm you)
