### ISSUE TITLE
Issues with Safari (iOS and Mac) when in Private Browsing mode

### ISSUE THREAD

**Issue by nhoizey** [marcuswestin/store.js#66]
It seems Private Browsing makes localStorage read only:
http://spin.atomicobject.com/2013/01/23/ios-private-browsing-localstorage/

When loading store.js, I get this error:
`QUOTA_EXCEEDED_ERR: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.`

I saw these lines in the lib:

```
try {
  store.set(namespace, namespace)
  if (store.get(namespace) != namespace) { store.disabled = true }
  store.remove(namespace)
} catch(e) {
  store.disabled = true
}
```

Maybe there's something to improve there…

**Comment by Download** [comment]
@marcuswestin I see on the README and in this issue that basically you are recommending devs to ask users to switch off Private Browsing mode, otherwise store.js will not function.

May I recommend my project, [memorystorage](http://download.github.io/memorystorage/) as an alternative to giving up? It's basically a polyfill for localStorage that's backed by regular memory. Sure, the data won't survive a browser reload, but there were never any guarantees anyway and at least the app will mostly work.

I'm currently using [Rhaboo](http://rhaboo.org/) in my project and it too failed in Private Browsing mode, so I hacked on it to get it fixed and ended up developing MemoryStorage as a fallback and it's been working great for me.

**Comment by marcuswestin** [comment]
Store.js v2.0 has been released with support for Safari private mode.

If you update to the latest version using the [v1 backcompatible build](https://github.com/marcuswestin/store.js/blob/master/dist/store.v1-backcompat.min.js) you will automatically get this functionality plus a bunch more :)
