### ISSUE TITLE
AMD implementation breaks sites

### ISSUE THREAD

**Issue by thomasbachem** [marcuswestin/store.js#78]
I finally found store.js while researching strange Javascript errors that I've encountered in my logs for some time now.

It seems like some quite popular Chrome plugin uses store.js, so it gets executed on my site even though I do not use store.js myself.

The problem is that store.js breaks my site! It confuses Dojo's AMD loader (and probably any other AMD loader too) when being loaded via a script tag in an AMD environment.

So when a page or browser plugin includes it via `<script src="store.min.js"></script>` when e.g. the Dojo Toolkit was loaded before, store.js will call `define(store)`, but the AMD loader will be unable to find out where that define came from and cannot determine any module ID. It will then fall back to the last used module ID, which can break things quite heavily.

So `define(store)` should be changed to `define('store', store)` to provide an explicit module ID.

**Comment by marcuswestin** [comment]
This may very well have been solved by 7c65e0a646c9c4743. @thomasbachem, can you please verify and/or close?

Thanks for the patience!

**Comment by Download** [comment]
I looked at the changes but I don't think they will make much difference. The new version still calls `define` and still does it anonymously...

I am not even sure the problem is solvable in the first place... From the script author's perspective he can never do it right:

* If he doesn't call `define` the script doesn't support AMD
* If he calls `define` without a name (so anonymous), this issue may be caused
* If he calls `define` with a name, he is going against the recommendations that AMD itself has put forth...

The general recommendation seems to be to either don't use AMD, or use it everywhere. I personally think that's a shame... Maybe they should be more forgiving in the case of `unmatched module` and just ignore those cases...

Changing to a named module now will break people using it via an AMD loader... So maybe all you can do is check for a flag to suppress the AMD call and convince the plugin guys to set that flag before using store.js...

**Comment by marcuswestin** [comment]
Sounds like there may not be a good solution at the end of the day :/ Feel free to reopen with more info.
